name: Reusable workflow

on:
  workflow_call:
    inputs:
      input-var:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "${{ inputs.input-var }}"
